---
title: "Research experience"
author: "zzj"
date: "2025-07-10"
output: html_document
---
## Academic achievements

-   Working paper: **Zhao, Z.**, Liu, H., Feng, Y., Chang, F., & Tang, B. The mediating role of short video viewing and other types of screen activities between parenting styles and children’s personality traits.(under submission)

-   Consultancy report: Liu, H., **Zhao, Z.**, & Feng, Y., (2024). Policy Recommendations on the Recruitment and Training of Publicly-funded Teacher Trainees.

-   Li, L., Liu, H., Kang, Y., Shi, Y., & **Zhao, Z**. (2024). The influence of parental involvement on students’non-cognitive abilities in rural ethnic regions of northwest China. Studies in Educational Evaluation, 81, 101344.https://doi.org/10.1016/j.stueduc.2024.101344


## Project experience

-  Horizontal Research Project: Enhancing Rural Education Quality through Innovation — The Rural Chief Teacher Dual-Teacher Live Classroom Project

    -  Research Project Participant: Conducted data cleaning for surveys, authored research reports
    
-  Horizontal Research Project: County-Level Promotion of Social-Emotional Activities for Rural Students

    -  Research Project Participant: Participation in project design, curriculum development, teacher training, procurement and mailing of teaching materials, design of questionnaires for students, teachers, and principals, field research, procurement of research materials, and data cleaning and processing.
    -  Participated in teacher training 3 times and curriculum development 4 times; as team leader, led 3 field research trips, covering a total of 30 schools, involving 30 principals, over 60 teachers, and more than 1,500 primary school students.
    
- Vertical Research Project: National Natural Science Foundation of China General Program: Dual-Teacher Classroom, Randomized Intervention Study on Non-Cognitive Abilities of Rural Chief Teachers and Rural Students

    -  Participated in standardized training on social-emotional curriculum content for rural primary school teachers, while responsible for monitoring, tracking, and providing feedback on the implementation of social-emotional courses by relevant teachers.
    
- Vertical Research Project: National Natural Science Foundation of China Youth Science Fund Project: Value-Added Evaluation Study of School and Teacher Quality Based on County-Level Compulsory Education Tracking Data

    -  Project Participant: Contributed to the construction of an integrated database combining administrative and survey data for primary and secondary students in a county-level region; engaged in the organization and integration of administrative data, as well as the cleaning and validation of survey data; participated in the design of questionnaires for students, teachers, and principals, and coordinated the procurement of survey materials and the organization and execution of field research.
    
    - The survey cumulatively covered 5 secondary schools and over 2,000 junior high school students.
    
##  Current Research Topics
Rural-urban education gap, school quality, teacher quality, child development, non-cognitive skills

##  Topics of interest
Generative AI, student development, labour market